name: yashika-s

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple command
        run: echo "Workflow is working!"

      -name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{secrets.AWS_ACCESS_KEY-ID}}
       aws-secret-access-key: ${{secrets._AWS_SECRET_ACCESS_KEY
       aws-region: us-east-1

       -name: Deploy static site to s3 bucket
       run: aws s3 sync . s3://yashii-bucket--delete

       
